name: Release

on:
  push:
    tags:
      - 'v*'

env:
  LINUX_TARGET: x86_64-unknown-linux-musl
  CARGO_PROFILE_RELEASE_OPT_LEVEL: 3
  CARGO_PROFILE_RELEASE_LTO: true
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
  CARGO_PROFILE_RELEASE_STRIP: true

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build linux
        run: |
          rustup target add ${{ env.LINUX_TARGET }}
          cargo build --release --target ${{ env.LINUX_TARGET }}
          cd target/${{ env.LINUX_TARGET }}/release/
          zip "${{github.workspace}}/blaise-${{ env.LINUX_TARGET }}.zip" blaise

      - uses: actions/upload-artifact@v3
        with:
          name: blaise-${{ env.LINUX_TARGET }}.zip
          path: "${{github.workspace}}/blaise-${{ env.LINUX_TARGET }}.zip"

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build macOS
        run: |
          cargo build --verbose --release
          cd target/release/
          zip "${{github.workspace}}/blaise-X86_64-macos.zip" blaise

      - uses: actions/upload-artifact@v3
        with:
          name: blaise-X86_64-macos.zip
          path: "${{github.workspace}}/blaise-X86_64-macos.zip"

  release:
    needs: [build_linux, build_macos]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set release tag
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#*refs/tags/v}" >> $GITHUB_ENV

      - name: Get linux release
        uses: actions/download-artifact@v4.1.7
        with:
          name: blaise-${{ env.LINUX_TARGET }}.zip

      - name: Get macos release
        uses: actions/download-artifact@v4.1.7
        with:
          name: blaise-X86_64-macos.zip

      - name: Complete release
        uses: sondreb/action-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          body: ''
          name: "Release ${{ env.RELEASE_TAG }}"
          tag: ${{ github.ref }}
          files: "blaise-${{ env.LINUX_TARGET }}.zip;blaise-X86_64-macos.zip"
